### PR TITLE
DaCapo

### PR DESCRIPTION
**Pull request by pattonw**
Add the DaCapo project.

This isn't quite ready for a merge.
Am I using the tags right? I added almost all microscopy tags since DaCapo can train on and segment pretty much any type of volumetric data.

I think we also need a nicer image to use for the card. At the moment I am using the DaCapo logo but it is too low resolution and the wrong aspect ratio so it gets way too zoomed in.

@rhoadesScholar, @mzouink, @avweigel, @StephanPreibisch, @funkey
Does this look good to you all?

### CODE REVIEW

**Comment by pattonw** [comment]
Screenshot 2024-10-29 at 7 31 03 PM

**Comment by allison-truhlar** [comment]
@pattonw I added a background to the Dacapo icon to improve the appearance - see screenshot which is of the largest size card.

Screenshot 2024-11-08 at 1 52 39 PM

As for the tags, each project is free to use them how they like. Their purpose is to make it possible for visitors browsing the site to discover new software related to a given topic. You can use this as a guide when deciding what tags to include - for example, if you want Dacapo to show up when someone is looking for software related to electron microscopy, etc., then I would include the tag. I hope this helps. Let me know if you have additional questions or when you're ready for me to merge the PR.

**Comment by pattonw** [comment]
Awesome, thanks for adding the background to the logo to improve the card. That looks great. I'll review the pull request with the rest of the team tomorrow and see if there are any other changes I need to make before merging. I should be able to let you know afternoon if we're ready to merge

**Comment by pattonw** [comment]
Good to go to merge this 👍 
Thanks!

**Review by allison-truhlar — APPROVED** [review]
Thank you for adding DaCapo to the site!

**Pull request merged**
