### PR TITLE
DVID: Adding project

### PR DESCRIPTION
**Pull request by DocSavage**
Some new tags were created in a limited fashion:

* `use case`: added `Connectomics` since that is a broad class of science at Janelia.
* `software ecosystem`: add `Neuroglancer` since the web app and storage formats are widely used in Connectomics and gaining traction in other areas of science.
* `supported file types`: added `Neuroglancer precomputed` because it is currently used for many image volumes and their corresponding segmentation. It could have been `Neuroglancer precomputed volume` to distinguish other neuroglancer formats like meshes and annotations.

### CODE REVIEW

**Comment by DocSavage** [comment]
I was thinking `Data service` would also be a broad `use case` similar to how `Visualization` is a category of tools (e.g., neuVid).

**Comment by allison-truhlar** [comment]
Thanks, @DocSavage, for making this PR and for the explanation around considering adding `Data service` as a new `use case` tag. With this additional perspective, I agree this would be a good use case to add in addition to `Connectomics`. Would you like me to go ahead and add it to your project file?

**Comment by DocSavage** [comment]
@allison-truhlar Done.

**Review by allison-truhlar — APPROVED** [review]
Thanks, Bill, for adding DVID!

**Pull request merged**
