### PR TITLE
added OSSI phases image

### LINKED ISSUE #251: OSSI phase diagram
Create a state diagram to illustrate phases of OSSI projects, and add to the OSSI About page. 

```mermaid
 graph TD;
      direction LR
      Proposed-->Accepted;
      Accepted-->AD{Active Development};
      AD{Active Development}-->Maintenance;
      Maintenance-->AD{Active Development};
```

### PR DESCRIPTION
**Pull request by krokicki**
To resolve #251.

### CODE REVIEW

**Comment by krokicki** [comment]
@allison-truhlar Can you please help me with adding this image to the OSSI about page?

**Comment by allison-truhlar** [comment]
@krokicki How does this look, before in terms of where the image is placed in the content and appearance? I didn't adjust the width of the image yet to match the text column, since this will change based on the resolution of issue #255.
OSSI-diagram-on-page

**Comment by krokicki** [comment]
Perfect, thanks! I will add context for it in the text and then we can merge this PR.

**Comment by krokicki** [comment]
@allison-truhlar Could you please review and merge this when you get a chance? Thank you!

**Review by allison-truhlar — APPROVED** [review]
Thanks for adding the diagram and text, Konrad! Both look great.

**Pull request merged**
